"""create initial tables

Revision ID: bd3e29c9b106
Revises: 20260609_0001
Create Date: 2026-06-16 13:24:27.641684
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bd3e29c9b106'
down_revision: str | None = '20260609_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
